services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: company
      POSTGRES_PASSWORD: company1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
